version: '3'

services:
  mysql:
    image: mysql:5.7
    platform: linux/x86_64
    container_name: amondz-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=10a10a
    command:
      - --character-set-server=utf8mb4 
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - amondz-net

  product-service:
    image: amondz/product-service
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: product-service
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - amondz-net

networks:
  amondz-net:
    driver: bridge